### ISSUE TITLE
Turning Idea.

### ISSUE THREAD

**Issue by Knoticator** [Spartronics4915/2016-Stronghold#167]
I think that having system that would allow us to turn and move forward at the same time would be extremely beneficial to the driving team. It would allow them to make corrections when lining up to a defense and for getting back to our side for Challenging or for picking up a moving ball.

Possible Sudo Code:

Get Joystick y and x.
divide y by x.
use that ratio to lower the speed of the motor on side that you want to turn towards.
if the ratio is in a certain range. then only go forward or only go left to keep a margin of error if you were only wanting to move forward.

**Comment by Knoticator** [comment]
Their might already be something like this

**Comment by dbadb** [comment]
I recommend that you look at the source code for RobotDrive... Specifically the tankDrive, arcadeDrive and drive methods all offer a variants of this.  You can find the source code here:

https://usfirst.collab.net/gerrit/allwpilib
